# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.srcs/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/urllc_core_smartconnect_outer_0.xci
# IP: The module: 'urllc_core_smartconnect_outer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/bd_e3a0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_0/bd_e3a0_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_1/bd_e3a0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_2/bd_e3a0_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_3/bd_e3a0_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_4/bd_e3a0_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_5/bd_e3a0_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_6/bd_e3a0_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_7/bd_e3a0_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_8/bd_e3a0_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_9/bd_e3a0_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_10/bd_e3a0_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_11/bd_e3a0_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_12/bd_e3a0_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_13/bd_e3a0_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_14/bd_e3a0_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_15/bd_e3a0_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_16/bd_e3a0_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_17/bd_e3a0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_18/bd_e3a0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_19/bd_e3a0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_20/bd_e3a0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_21/bd_e3a0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_22/bd_e3a0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_23/bd_e3a0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_24/bd_e3a0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_25/bd_e3a0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_26/bd_e3a0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_27/bd_e3a0_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_28/bd_e3a0_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_29/bd_e3a0_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_30/bd_e3a0_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_31/bd_e3a0_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_32/bd_e3a0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_33/bd_e3a0_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_34/bd_e3a0_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_35/bd_e3a0_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_36/bd_e3a0_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_37/bd_e3a0_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_38/bd_e3a0_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_39/bd_e3a0_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_40/bd_e3a0_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_41/bd_e3a0_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_42/bd_e3a0_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_43/bd_e3a0_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_44/bd_e3a0_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_45/bd_e3a0_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_46/bd_e3a0_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_47/bd_e3a0_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_48/bd_e3a0_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_49/bd_e3a0_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_50/bd_e3a0_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_51/bd_e3a0_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_52/bd_e3a0_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_53/bd_e3a0_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_1/bd_e3a0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_1/bd_e3a0_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_2/bd_e3a0_arinsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_3/bd_e3a0_rinsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_4/bd_e3a0_awinsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_5/bd_e3a0_winsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_6/bd_e3a0_binsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_7/bd_e3a0_aroutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_8/bd_e3a0_routsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_9/bd_e3a0_awoutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_10/bd_e3a0_woutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_11/bd_e3a0_boutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_12/bd_e3a0_arni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_13/bd_e3a0_rni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_14/bd_e3a0_awni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_15/bd_e3a0_wni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_16/bd_e3a0_bni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_20/bd_e3a0_s00a2s_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_21/bd_e3a0_sarn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_22/bd_e3a0_srn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_23/bd_e3a0_sawn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_24/bd_e3a0_swn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_25/bd_e3a0_sbn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_26/bd_e3a0_m00s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_27/bd_e3a0_m00arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_28/bd_e3a0_m00rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_29/bd_e3a0_m00awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_30/bd_e3a0_m00wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_31/bd_e3a0_m00bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_33/bd_e3a0_m01s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_34/bd_e3a0_m01arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_35/bd_e3a0_m01rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_36/bd_e3a0_m01awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_37/bd_e3a0_m01wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_38/bd_e3a0_m01bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_40/bd_e3a0_m02s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_41/bd_e3a0_m02arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_42/bd_e3a0_m02rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_43/bd_e3a0_m02awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_44/bd_e3a0_m02wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_45/bd_e3a0_m02bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_47/bd_e3a0_m03s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_48/bd_e3a0_m03arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_49/bd_e3a0_m03rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_50/bd_e3a0_m03awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_51/bd_e3a0_m03wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_52/bd_e3a0_m03bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_core_smartconnect_outer_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.srcs/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/urllc_core_smartconnect_outer_0.xci
# IP: The module: 'urllc_core_smartconnect_outer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/bd_e3a0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_0/bd_e3a0_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_1/bd_e3a0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_2/bd_e3a0_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_3/bd_e3a0_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_4/bd_e3a0_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_5/bd_e3a0_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_6/bd_e3a0_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_7/bd_e3a0_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_8/bd_e3a0_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_9/bd_e3a0_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_10/bd_e3a0_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_11/bd_e3a0_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_12/bd_e3a0_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_13/bd_e3a0_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_14/bd_e3a0_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_15/bd_e3a0_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_16/bd_e3a0_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_17/bd_e3a0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_18/bd_e3a0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_19/bd_e3a0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_20/bd_e3a0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_21/bd_e3a0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_22/bd_e3a0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_23/bd_e3a0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_24/bd_e3a0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_25/bd_e3a0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_26/bd_e3a0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_27/bd_e3a0_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_28/bd_e3a0_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_29/bd_e3a0_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_30/bd_e3a0_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_31/bd_e3a0_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_32/bd_e3a0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_33/bd_e3a0_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_34/bd_e3a0_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_35/bd_e3a0_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_36/bd_e3a0_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_37/bd_e3a0_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_38/bd_e3a0_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_39/bd_e3a0_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_40/bd_e3a0_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_41/bd_e3a0_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_42/bd_e3a0_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_43/bd_e3a0_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_44/bd_e3a0_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_45/bd_e3a0_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_46/bd_e3a0_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_47/bd_e3a0_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_48/bd_e3a0_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_49/bd_e3a0_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_50/bd_e3a0_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_51/bd_e3a0_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_52/bd_e3a0_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_53/bd_e3a0_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_1/bd_e3a0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_1/bd_e3a0_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_2/bd_e3a0_arinsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_3/bd_e3a0_rinsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_4/bd_e3a0_awinsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_5/bd_e3a0_winsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_6/bd_e3a0_binsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_7/bd_e3a0_aroutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_8/bd_e3a0_routsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_9/bd_e3a0_awoutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_10/bd_e3a0_woutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_11/bd_e3a0_boutsw_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_12/bd_e3a0_arni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_13/bd_e3a0_rni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_14/bd_e3a0_awni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_15/bd_e3a0_wni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_16/bd_e3a0_bni_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_20/bd_e3a0_s00a2s_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_21/bd_e3a0_sarn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_22/bd_e3a0_srn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_23/bd_e3a0_sawn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_24/bd_e3a0_swn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_25/bd_e3a0_sbn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_26/bd_e3a0_m00s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_27/bd_e3a0_m00arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_28/bd_e3a0_m00rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_29/bd_e3a0_m00awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_30/bd_e3a0_m00wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_31/bd_e3a0_m00bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_33/bd_e3a0_m01s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_34/bd_e3a0_m01arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_35/bd_e3a0_m01rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_36/bd_e3a0_m01awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_37/bd_e3a0_m01wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_38/bd_e3a0_m01bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_40/bd_e3a0_m02s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_41/bd_e3a0_m02arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_42/bd_e3a0_m02rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_43/bd_e3a0_m02awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_44/bd_e3a0_m02wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_45/bd_e3a0_m02bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_47/bd_e3a0_m03s2a_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_48/bd_e3a0_m03arn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_49/bd_e3a0_m03rn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_50/bd_e3a0_m03awn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_51/bd_e3a0_m03wn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/bd_0/ip/ip_52/bd_e3a0_m03bn_0_ooc.xdc

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/urllc_core/ip/urllc_core_smartconnect_outer_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_core_smartconnect_outer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
