# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/srcs/urllc.xdc

# Block Designs: bd/urllc_fifo_core/urllc_fifo_core.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core || ORIG_REF_NAME==urllc_fifo_core} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_DDCWrapper_0_0/urllc_fifo_core_DDCWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_DDCWrapper_0_0 || ORIG_REF_NAME==urllc_fifo_core_DDCWrapper_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlconcat_0_0/urllc_fifo_core_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlconcat_0_0 || ORIG_REF_NAME==urllc_fifo_core_xlconcat_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlconstant_0_0/urllc_fifo_core_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlconstant_0_0 || ORIG_REF_NAME==urllc_fifo_core_xlconstant_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_axi_dma_0_0/urllc_fifo_core_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_axi_dma_0_0 || ORIG_REF_NAME==urllc_fifo_core_axi_dma_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_clk_dynamic_0/urllc_fifo_core_clk_dynamic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_clk_dynamic_0 || ORIG_REF_NAME==urllc_fifo_core_clk_dynamic_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_clk_static_0/urllc_fifo_core_clk_static_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_clk_static_0 || ORIG_REF_NAME==urllc_fifo_core_clk_static_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_processing_system7_0_0/urllc_fifo_core_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_processing_system7_0_0 || ORIG_REF_NAME==urllc_fifo_core_processing_system7_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xbar_0/urllc_fifo_core_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xbar_0 || ORIG_REF_NAME==urllc_fifo_core_xbar_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_ps7_0_axi_periph_0/urllc_fifo_core_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_ps7_0_axi_periph_0 || ORIG_REF_NAME==urllc_fifo_core_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_reset_dynamic_0/urllc_fifo_core_reset_dynamic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_reset_dynamic_0 || ORIG_REF_NAME==urllc_fifo_core_reset_dynamic_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_reset_static_0/urllc_fifo_core_reset_static_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_reset_static_0 || ORIG_REF_NAME==urllc_fifo_core_reset_static_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlconcat_irq_0/urllc_fifo_core_xlconcat_irq_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlconcat_irq_0 || ORIG_REF_NAME==urllc_fifo_core_xlconcat_irq_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_DUCWrapper_0_0/urllc_fifo_core_DUCWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_DUCWrapper_0_0 || ORIG_REF_NAME==urllc_fifo_core_DUCWrapper_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_mux_reciever_out_0/urllc_fifo_core_mux_reciever_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_mux_reciever_out_0 || ORIG_REF_NAME==urllc_fifo_core_mux_reciever_out_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_sender_0/urllc_fifo_core_xlslice_sender_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_sender_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_sender_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_axi_gpio_0_0/urllc_fifo_core_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_axi_gpio_0_0 || ORIG_REF_NAME==urllc_fifo_core_axi_gpio_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_adc_0_7_0/urllc_fifo_core_xlslice_adc_0_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_adc_0_7_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_adc_0_7_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_clk_psclk_3_0/urllc_fifo_core_xlslice_clk_psclk_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_clk_psclk_3_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_clk_psclk_3_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_clk_psen_4_0/urllc_fifo_core_xlslice_clk_psen_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_clk_psen_4_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_clk_psen_4_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_clk_psincdec_5_0/urllc_fifo_core_xlslice_clk_psincdec_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_clk_psincdec_5_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_clk_psincdec_5_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_count_trigger_clear_0_0/urllc_fifo_core_xlslice_count_trigger_clear_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_count_trigger_clear_0_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_count_trigger_clear_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_counter_trigger_16_31_0/urllc_fifo_core_xlslice_counter_trigger_16_31_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_counter_trigger_16_31_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_counter_trigger_16_31_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_dac_8_15_0/urllc_fifo_core_xlslice_dac_8_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_dac_8_15_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_dac_8_15_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_ddc_sync_8_0/urllc_fifo_core_xlslice_ddc_sync_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_ddc_sync_8_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_ddc_sync_8_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_duc_sync_6_0/urllc_fifo_core_xlslice_duc_sync_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_duc_sync_6_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_duc_sync_6_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_fifo_read_start_2_0/urllc_fifo_core_xlslice_fifo_read_start_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_fifo_read_start_2_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_fifo_read_start_2_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_fifo_write_start_1_0/urllc_fifo_core_xlslice_fifo_write_start_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_fifo_write_start_1_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_fifo_write_start_1_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_reciever_in_9_0/urllc_fifo_core_xlslice_reciever_in_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_reciever_in_9_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_reciever_in_9_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_reciever_out_7_0/urllc_fifo_core_xlslice_reciever_out_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_reciever_out_7_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_reciever_out_7_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlconstant_0_1/urllc_fifo_core_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlconstant_0_1 || ORIG_REF_NAME==urllc_fifo_core_xlconstant_0_1} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_reciever_in_9_1/urllc_fifo_core_xlslice_reciever_in_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_reciever_in_9_1 || ORIG_REF_NAME==urllc_fifo_core_xlslice_reciever_in_9_1} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlslice_adc_fifo_reset_10_0/urllc_fifo_core_xlslice_adc_fifo_reset_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlslice_adc_fifo_reset_10_0 || ORIG_REF_NAME==urllc_fifo_core_xlslice_adc_fifo_reset_10_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/urllc_fifo_core_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_system_ila_0_0 || ORIG_REF_NAME==urllc_fifo_core_system_ila_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xbar_1/urllc_fifo_core_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xbar_1 || ORIG_REF_NAME==urllc_fifo_core_xbar_1} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_axi_interconnect_0_0/urllc_fifo_core_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_axi_interconnect_0_0 || ORIG_REF_NAME==urllc_fifo_core_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_adc_axis_0_0/urllc_fifo_core_adc_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_adc_axis_0_0 || ORIG_REF_NAME==urllc_fifo_core_adc_axis_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_axis_data_fifo_0_0/urllc_fifo_core_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_axis_data_fifo_0_0 || ORIG_REF_NAME==urllc_fifo_core_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_axis_data_fifo_adc_1/urllc_fifo_core_axis_data_fifo_adc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_axis_data_fifo_adc_1 || ORIG_REF_NAME==urllc_fifo_core_axis_data_fifo_adc_1} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_dac_axis_0_0/urllc_fifo_core_dac_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_dac_axis_0_0 || ORIG_REF_NAME==urllc_fifo_core_dac_axis_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_mux_adc_fifo_reset_0/urllc_fifo_core_mux_adc_fifo_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_mux_adc_fifo_reset_0 || ORIG_REF_NAME==urllc_fifo_core_mux_adc_fifo_reset_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_mux_dac_fifo_reset_0/urllc_fifo_core_mux_dac_fifo_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_mux_dac_fifo_reset_0 || ORIG_REF_NAME==urllc_fifo_core_mux_dac_fifo_reset_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_mux_0_0/urllc_fifo_core_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_mux_0_0 || ORIG_REF_NAME==urllc_fifo_core_mux_0_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_xlconstant_0_2/urllc_fifo_core_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_xlconstant_0_2 || ORIG_REF_NAME==urllc_fifo_core_xlconstant_0_2} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_mux_0_1/urllc_fifo_core_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_mux_0_1 || ORIG_REF_NAME==urllc_fifo_core_mux_0_1} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_auto_pc_0/urllc_fifo_core_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_auto_pc_0 || ORIG_REF_NAME==urllc_fifo_core_auto_pc_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_0/urllc_fifo_core_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_auto_us_0 || ORIG_REF_NAME==urllc_fifo_core_auto_us_0} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_1/urllc_fifo_core_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_auto_us_1 || ORIG_REF_NAME==urllc_fifo_core_auto_us_1} -quiet] -quiet

# IP: bd/urllc_fifo_core/ip/urllc_fifo_core_auto_pc_1/urllc_fifo_core_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==urllc_fifo_core_auto_pc_1 || ORIG_REF_NAME==urllc_fifo_core_auto_pc_1} -quiet] -quiet

# XDC: bd/urllc_fifo_core/urllc_fifo_core_ooc.xdc
