# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.cache/wt [current_project]
set_property parent.project_path D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/new/sender_wrapper.v
add_files D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/urllc_fifo_core.bd
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axi_dma_0_0/urllc_fifo_core_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axi_dma_0_0/urllc_fifo_core_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axi_dma_0_0/urllc_fifo_core_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_clk_dynamic_0/urllc_fifo_core_clk_dynamic_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_clk_dynamic_0/urllc_fifo_core_clk_dynamic_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_clk_dynamic_0/urllc_fifo_core_clk_dynamic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_clk_static_0/urllc_fifo_core_clk_static_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_clk_static_0/urllc_fifo_core_clk_static_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_clk_static_0/urllc_fifo_core_clk_static_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_processing_system7_0_0/urllc_fifo_core_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_xbar_0/urllc_fifo_core_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_reset_dynamic_0/urllc_fifo_core_reset_dynamic_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_reset_dynamic_0/urllc_fifo_core_reset_dynamic_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_reset_dynamic_0/urllc_fifo_core_reset_dynamic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_reset_static_0/urllc_fifo_core_reset_static_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_reset_static_0/urllc_fifo_core_reset_static_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_reset_static_0/urllc_fifo_core_reset_static_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axi_gpio_0_0/urllc_fifo_core_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axi_gpio_0_0/urllc_fifo_core_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axi_gpio_0_0/urllc_fifo_core_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/urllc_fifo_core_system_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/bd_0/ip/ip_0/bd_d2de_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_system_ila_0_0/bd_0/bd_d2de_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_xbar_1/urllc_fifo_core_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axis_data_fifo_0_0/urllc_fifo_core_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_axis_data_fifo_adc_1/urllc_fifo_core_axis_data_fifo_adc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_pc_0/urllc_fifo_core_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_0/urllc_fifo_core_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_0/urllc_fifo_core_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_0/urllc_fifo_core_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_1/urllc_fifo_core_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_1/urllc_fifo_core_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_us_1/urllc_fifo_core_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/ip/urllc_fifo_core_auto_pc_1/urllc_fifo_core_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/urllc_fifo_core/urllc_fifo_core_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/constrs_1/imports/srcs/urllc.xdc
set_property used_in_implementation false [get_files D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/constrs_1/imports/srcs/urllc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sender_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sender_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sender_wrapper_utilization_synth.rpt -pb sender_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
