# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.srcs/sources_1/bd/urllc/ip/urllc_processing_system7_0_0/urllc_processing_system7_0_0.xci
# IP: The module: 'urllc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.gen/sources_1/bd/urllc/ip/urllc_processing_system7_0_0/urllc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: h:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.srcs/sources_1/bd/urllc/ip/urllc_processing_system7_0_0/urllc_processing_system7_0_0.xci
# IP: The module: 'urllc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.gen/sources_1/bd/urllc/ip/urllc_processing_system7_0_0/urllc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
