# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.srcs/sources_1/bd/urllc/ip/urllc_xbar_3/urllc_xbar_3.xci
# IP: The module: 'urllc_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.gen/sources_1/bd/urllc/ip/urllc_xbar_3/urllc_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: H:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.srcs/sources_1/bd/urllc/ip/urllc_xbar_3/urllc_xbar_3.xci
# IP: The module: 'urllc_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Chiro/gits/urllc-demo-pynq/urllc-demo-vivado/urllc-demo-vivado.gen/sources_1/bd/urllc/ip/urllc_xbar_3/urllc_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
