# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0.xci
# IP: The module: 'urllc_fifo_core_inst_1_clk_static_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_fifo_core_inst_1_clk_static_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_fifo_core_inst_1_clk_static_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_fifo_core_inst_1_clk_static_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0.xci
# IP: The module: 'urllc_fifo_core_inst_1_clk_static_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_fifo_core_inst_1_clk_static_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_fifo_core_inst_1_clk_static_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/bd/urllc_fifo_core_inst_1/ip/urllc_fifo_core_inst_1_clk_static_0/urllc_fifo_core_inst_1_clk_static_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'urllc_fifo_core_inst_1_clk_static_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
