-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ad2dma is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    inputs_TVALID : IN STD_LOGIC;
    outs_TREADY : IN STD_LOGIC;
    ad_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ad_ce0 : OUT STD_LOGIC;
    ad_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    da_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    da_ce0 : OUT STD_LOGIC;
    da_we0 : OUT STD_LOGIC;
    da_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    inputs_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    inputs_TREADY : OUT STD_LOGIC;
    inputs_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    inputs_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    inputs_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    inputs_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    inputs_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    inputs_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    outs_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    outs_TVALID : OUT STD_LOGIC;
    outs_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    outs_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    outs_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    outs_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    outs_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    outs_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of ad2dma is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ad2dma_ad2dma,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.085000,HLS_SYN_LAT=203,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=61,HLS_SYN_LUT=112,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_C8 : STD_LOGIC_VECTOR (7 downto 0) := "11001000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal icmp_ln11_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_outs_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal inputs_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal outs_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_1_reg_227 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_reg_232 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_reg_237 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_247 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_cast_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_82 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln11_fu_170_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal regslice_both_inputs_V_data_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal inputs_TVALID_int_regslice : STD_LOGIC;
    signal inputs_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_inputs_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inputs_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_inputs_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inputs_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inputs_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_inputs_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inputs_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inputs_V_user_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_inputs_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inputs_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inputs_V_last_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_inputs_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inputs_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inputs_V_id_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_inputs_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inputs_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inputs_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal inputs_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_inputs_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inputs_V_dest_V_U_ack_in : STD_LOGIC;
    signal outs_TVALID_int_regslice : STD_LOGIC;
    signal outs_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_outs_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outs_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outs_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outs_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outs_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outs_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outs_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outs_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outs_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outs_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outs_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outs_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outs_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outs_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outs_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outs_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outs_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outs_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outs_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_191 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component ad2dma_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component ad2dma_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component ad2dma_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component ad2dma_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    flow_control_loop_pipe_U : component ad2dma_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);

    regslice_both_inputs_V_data_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TDATA,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_data_V_U_ack_in,
        data_out => inputs_TDATA_int_regslice,
        vld_out => inputs_TVALID_int_regslice,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_data_V_U_apdone_blk);

    regslice_both_inputs_V_keep_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TKEEP,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_keep_V_U_ack_in,
        data_out => inputs_TKEEP_int_regslice,
        vld_out => regslice_both_inputs_V_keep_V_U_vld_out,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_keep_V_U_apdone_blk);

    regslice_both_inputs_V_strb_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TSTRB,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_strb_V_U_ack_in,
        data_out => inputs_TSTRB_int_regslice,
        vld_out => regslice_both_inputs_V_strb_V_U_vld_out,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_strb_V_U_apdone_blk);

    regslice_both_inputs_V_user_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TUSER,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_user_V_U_ack_in,
        data_out => inputs_TUSER_int_regslice,
        vld_out => regslice_both_inputs_V_user_V_U_vld_out,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_user_V_U_apdone_blk);

    regslice_both_inputs_V_last_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TLAST,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_last_V_U_ack_in,
        data_out => inputs_TLAST_int_regslice,
        vld_out => regslice_both_inputs_V_last_V_U_vld_out,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_last_V_U_apdone_blk);

    regslice_both_inputs_V_id_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TID,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_id_V_U_ack_in,
        data_out => inputs_TID_int_regslice,
        vld_out => regslice_both_inputs_V_id_V_U_vld_out,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_id_V_U_apdone_blk);

    regslice_both_inputs_V_dest_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inputs_TDEST,
        vld_in => inputs_TVALID,
        ack_in => regslice_both_inputs_V_dest_V_U_ack_in,
        data_out => inputs_TDEST_int_regslice,
        vld_out => regslice_both_inputs_V_dest_V_U_vld_out,
        ack_out => inputs_TREADY_int_regslice,
        apdone_blk => regslice_both_inputs_V_dest_V_U_apdone_blk);

    regslice_both_outs_V_data_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ad_q0,
        vld_in => outs_TVALID_int_regslice,
        ack_in => outs_TREADY_int_regslice,
        data_out => outs_TDATA,
        vld_out => regslice_both_outs_V_data_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_data_V_U_apdone_blk);

    regslice_both_outs_V_keep_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_1_reg_227,
        vld_in => outs_TVALID_int_regslice,
        ack_in => regslice_both_outs_V_keep_V_U_ack_in_dummy,
        data_out => outs_TKEEP,
        vld_out => regslice_both_outs_V_keep_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_keep_V_U_apdone_blk);

    regslice_both_outs_V_strb_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_2_reg_232,
        vld_in => outs_TVALID_int_regslice,
        ack_in => regslice_both_outs_V_strb_V_U_ack_in_dummy,
        data_out => outs_TSTRB,
        vld_out => regslice_both_outs_V_strb_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_strb_V_U_apdone_blk);

    regslice_both_outs_V_user_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_3_reg_237,
        vld_in => outs_TVALID_int_regslice,
        ack_in => regslice_both_outs_V_user_V_U_ack_in_dummy,
        data_out => outs_TUSER,
        vld_out => regslice_both_outs_V_user_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_user_V_U_apdone_blk);

    regslice_both_outs_V_last_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_4_reg_242,
        vld_in => outs_TVALID_int_regslice,
        ack_in => regslice_both_outs_V_last_V_U_ack_in_dummy,
        data_out => outs_TLAST,
        vld_out => regslice_both_outs_V_last_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_last_V_U_apdone_blk);

    regslice_both_outs_V_id_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_5_reg_247,
        vld_in => outs_TVALID_int_regslice,
        ack_in => regslice_both_outs_V_id_V_U_ack_in_dummy,
        data_out => outs_TID,
        vld_out => regslice_both_outs_V_id_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_id_V_U_apdone_blk);

    regslice_both_outs_V_dest_V_U : component ad2dma_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_6_reg_252,
        vld_in => outs_TVALID_int_regslice,
        ack_in => regslice_both_outs_V_dest_V_U_ack_in_dummy,
        data_out => outs_TDEST,
        vld_out => regslice_both_outs_V_dest_V_U_vld_out,
        ack_out => outs_TREADY,
        apdone_blk => regslice_both_outs_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_191)) then
                if ((icmp_ln11_fu_164_p2 = ap_const_lv1_0)) then 
                    i_fu_82 <= add_ln11_fu_170_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_82 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_1_reg_227 <= inputs_TKEEP_int_regslice;
                tmp_2_reg_232 <= inputs_TSTRB_int_regslice;
                tmp_3_reg_237 <= inputs_TUSER_int_regslice;
                tmp_4_reg_242 <= inputs_TLAST_int_regslice;
                tmp_5_reg_247 <= inputs_TID_int_regslice;
                tmp_6_reg_252 <= inputs_TDEST_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ad_address0 <= i_cast_fu_176_p1(8 - 1 downto 0);

    ad_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ad_ce0 <= ap_const_logic_1;
        else 
            ad_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln11_fu_170_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln11_fu_164_p2, regslice_both_outs_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, inputs_TVALID_int_regslice, outs_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1) or (outs_TREADY_int_regslice = ap_const_logic_0))) or ((icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (inputs_TVALID_int_regslice = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)) or ((outs_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln11_fu_164_p2, regslice_both_outs_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, inputs_TVALID_int_regslice, outs_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1) or (outs_TREADY_int_regslice = ap_const_logic_0))) or ((icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (inputs_TVALID_int_regslice = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)) or ((outs_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln11_fu_164_p2, regslice_both_outs_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, inputs_TVALID_int_regslice, outs_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1) or (outs_TREADY_int_regslice = ap_const_logic_0))) or ((icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (inputs_TVALID_int_regslice = ap_const_logic_0) and (ap_start_int = ap_const_logic_1)) or ((outs_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln11_fu_164_p2, inputs_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (inputs_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_both_outs_V_data_V_U_apdone_blk, outs_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_outs_V_data_V_U_apdone_blk = ap_const_logic_1) or (outs_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(outs_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (outs_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_191_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_191 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln11_fu_164_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln11_fu_164_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_exit_ready_pp0_iter1_reg, ap_block_pp0_stage0_subdone, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_82, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_82;
        end if; 
    end process;

    da_address0 <= i_cast_fu_176_p1(8 - 1 downto 0);

    da_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            da_ce0 <= ap_const_logic_1;
        else 
            da_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    da_d0 <= inputs_TDATA_int_regslice;

    da_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln11_fu_164_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            da_we0 <= ap_const_logic_1;
        else 
            da_we0 <= ap_const_logic_0;
        end if; 
    end process;

    i_cast_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
    icmp_ln11_fu_164_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv8_C8) else "0";

    inputs_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln11_fu_164_p2, ap_block_pp0_stage0, ap_start_int, inputs_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inputs_TDATA_blk_n <= inputs_TVALID_int_regslice;
        else 
            inputs_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    inputs_TREADY <= regslice_both_inputs_V_data_V_U_ack_in;

    inputs_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln11_fu_164_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_fu_164_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inputs_TREADY_int_regslice <= ap_const_logic_1;
        else 
            inputs_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    outs_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, outs_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            outs_TDATA_blk_n <= outs_TREADY_int_regslice;
        else 
            outs_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outs_TVALID <= regslice_both_outs_V_data_V_U_vld_out;

    outs_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            outs_TVALID_int_regslice <= ap_const_logic_1;
        else 
            outs_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
