#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : design_sender.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Jan 13 06:04:06 +0800 2022
# SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_sender.sh [-help]
# usage: design_sender.sh [-lib_map_path]
# usage: design_sender.sh [-noclean_files]
# usage: design_sender.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_sender.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_26 axi_sg_v4_1_13 axi_dma_v7_1_25 xil_defaultlib xlconcat_v2_1_4 xlconstant_v1_1_7 xlslice_v1_0_2 proc_sys_reset_v5_0_13 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_26 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_24 axi_vip_v1_1_10 processing_system7_vip_v1_0_12)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_sender.sh - Script generated by export_simulation (Vivado v2021.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_26 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/1e21/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_25 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/1faa/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_axi_dma_1_0/sim/urllc_core_inst_1_axi_dma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_1_0/sim/urllc_core_inst_1_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconstant_1_0/sim/urllc_core_inst_1_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_1_0/sim/urllc_core_inst_1_xlslice_1_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_DDCWrapper_0_0/sim/urllc_core_inst_1_DDCWrapper_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_rst_ps7_0_200M_0/sim/urllc_core_inst_1_rst_ps7_0_200M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconstant_0_0/sim/urllc_core_inst_1_xlconstant_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_0_0/sim/urllc_core_inst_1_xlconcat_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_mux_0_0/sim/urllc_core_inst_1_mux_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_mux_1_0/sim/urllc_core_inst_1_mux_1_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_mux_3_0/sim/urllc_core_inst_1_mux_3_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_ad2dma_rtl_0_0/sim/urllc_core_inst_1_ad2dma_rtl_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_div_n_0_0/sim/urllc_core_inst_1_div_n_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_mux_rtl_0/sim/urllc_core_inst_1_mux_rtl_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_ad_buf_0_0/sim/urllc_core_inst_1_ad_buf_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_axi_dma_0_0/sim/urllc_core_inst_1_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_0_1/sim/urllc_core_inst_1_xlconcat_0_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconstant_0_1/sim/urllc_core_inst_1_xlconstant_0_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_0_0/sim/urllc_core_inst_1_xlslice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_rst_ps7_0_120M_0/sim/urllc_core_inst_1_rst_ps7_0_120M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_1_1/sim/urllc_core_inst_1_xlconcat_1_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconstant_1_1/sim/urllc_core_inst_1_xlconstant_1_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_ad2dma_rtl_0_1/sim/urllc_core_inst_1_ad2dma_rtl_0_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_DUCWrapper_0_0/sim/urllc_core_inst_1_DUCWrapper_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_mux_0_1/sim/urllc_core_inst_1_mux_0_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_irq_0/sim/urllc_core_inst_1_xlconcat_irq_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_3_use_sender_iq_0/sim/urllc_core_inst_1_xlslice_3_use_sender_iq_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_1_use_sender_serial_0/sim/urllc_core_inst_1_xlslice_1_use_sender_serial_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_0_fun_out_0/sim/urllc_core_inst_1_xlslice_0_fun_out_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_2_disable_sync_0/sim/urllc_core_inst_1_xlslice_2_disable_sync_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_26 $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/65b4/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_axi_gpio_0_0/sim/urllc_core_inst_1_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_0_2/sim/urllc_core_inst_1_xlconcat_0_2.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_4_psclk_0/sim/urllc_core_inst_1_xlslice_4_psclk_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_5_psen_0/sim/urllc_core_inst_1_xlslice_5_psen_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlslice_6_psincdec_0/sim/urllc_core_inst_1_xlslice_6_psincdec_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_ila_0_0/sim/urllc_core_inst_1_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_proc_clock_reset_0/sim/urllc_core_inst_1_proc_clock_reset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_static_0/urllc_core_inst_1_clk_wiz_static_0_clk_wiz.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_static_0/urllc_core_inst_1_clk_wiz_static_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_proc_data_reset_8M_0/sim/urllc_core_inst_1_proc_data_reset_8M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_0/sim/bd_a535_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_1/sim/bd_a535_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_2/sim/bd_a535_arinsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_3/sim/bd_a535_rinsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_4/sim/bd_a535_awinsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_5/sim/bd_a535_winsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_6/sim/bd_a535_binsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_7/sim/bd_a535_aroutsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_8/sim/bd_a535_routsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_9/sim/bd_a535_awoutsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_10/sim/bd_a535_woutsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_11/sim/bd_a535_boutsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_12/sim/bd_a535_arni_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_13/sim/bd_a535_rni_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_14/sim/bd_a535_awni_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_15/sim/bd_a535_wni_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_16/sim/bd_a535_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_17/sim/bd_a535_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_18/sim/bd_a535_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_19/sim/bd_a535_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_20/sim/bd_a535_s00a2s_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_21/sim/bd_a535_sarn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_22/sim/bd_a535_srn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_23/sim/bd_a535_sawn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_24/sim/bd_a535_swn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_25/sim/bd_a535_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_26/sim/bd_a535_m00s2a_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_27/sim/bd_a535_m00arn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_28/sim/bd_a535_m00rn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_29/sim/bd_a535_m00awn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_30/sim/bd_a535_m00wn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_31/sim/bd_a535_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_32/sim/bd_a535_m00e_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_33/sim/bd_a535_m01s2a_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_34/sim/bd_a535_m01arn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_35/sim/bd_a535_m01rn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_36/sim/bd_a535_m01awn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_37/sim/bd_a535_m01wn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_38/sim/bd_a535_m01bn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_39/sim/bd_a535_m01e_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_40/sim/bd_a535_m02s2a_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_41/sim/bd_a535_m02arn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_42/sim/bd_a535_m02rn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_43/sim/bd_a535_m02awn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_44/sim/bd_a535_m02wn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_45/sim/bd_a535_m02bn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/ip/ip_46/sim/bd_a535_m02e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/bd_0/sim/bd_a535.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/8f68/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/0980/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_0/sim/urllc_core_inst_1_smartconnect_outer_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/urllc_core_inst_1_clk_wiz_dynamic_0_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_ipif_pkg.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_family_support.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_family.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_soft_reset.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/proc_common_v3_00_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_pselect_f.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_address_decoder.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_slave_attachment.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/urllc_core_inst_1_clk_wiz_dynamic_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/urllc_core_inst_1_clk_wiz_dynamic_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/urllc_core_inst_1_clk_wiz_dynamic_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/urllc_core_inst_1_clk_wiz_dynamic_0_clk_wiz.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_dynamic_0/urllc_core_inst_1_clk_wiz_dynamic_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_xlconcat_0_3/sim/urllc_core_inst_1_xlconcat_0_3.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_100M_0/urllc_core_inst_1_clk_wiz_100M_0_clk_wiz.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_clk_wiz_100M_0/urllc_core_inst_1_clk_wiz_100M_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_processing_system7_0_0/sim/urllc_core_inst_1_processing_system7_0_0.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_0/sim/bd_65f4_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_1/sim/bd_65f4_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_2/sim/bd_65f4_arsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_3/sim/bd_65f4_rsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_4/sim/bd_65f4_awsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_5/sim/bd_65f4_wsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_6/sim/bd_65f4_bsw_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_7/sim/bd_65f4_s00mmu_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_8/sim/bd_65f4_s00tr_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_9/sim/bd_65f4_s00sic_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_10/sim/bd_65f4_s00a2s_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_11/sim/bd_65f4_sarn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_12/sim/bd_65f4_srn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_13/sim/bd_65f4_sawn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_14/sim/bd_65f4_swn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_15/sim/bd_65f4_sbn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_16/sim/bd_65f4_s01mmu_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_17/sim/bd_65f4_s01tr_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_18/sim/bd_65f4_s01sic_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_19/sim/bd_65f4_s01a2s_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_20/sim/bd_65f4_sarn_1.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_21/sim/bd_65f4_srn_1.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_22/sim/bd_65f4_s02mmu_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_23/sim/bd_65f4_s02tr_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_24/sim/bd_65f4_s02sic_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_25/sim/bd_65f4_s02a2s_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_26/sim/bd_65f4_sawn_1.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_27/sim/bd_65f4_swn_1.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_28/sim/bd_65f4_sbn_1.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_29/sim/bd_65f4_s03mmu_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_30/sim/bd_65f4_s03tr_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_31/sim/bd_65f4_s03sic_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_32/sim/bd_65f4_s03a2s_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_33/sim/bd_65f4_sarn_2.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_34/sim/bd_65f4_srn_2.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_35/sim/bd_65f4_s04mmu_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_36/sim/bd_65f4_s04tr_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_37/sim/bd_65f4_s04sic_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_38/sim/bd_65f4_s04a2s_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_39/sim/bd_65f4_sawn_2.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_40/sim/bd_65f4_swn_2.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_41/sim/bd_65f4_sbn_2.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_42/sim/bd_65f4_m00s2a_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_43/sim/bd_65f4_m00arn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_44/sim/bd_65f4_m00rn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_45/sim/bd_65f4_m00awn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_46/sim/bd_65f4_m00wn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_47/sim/bd_65f4_m00bn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_48/sim/bd_65f4_m00e_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_49/sim/bd_65f4_m01s2a_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_50/sim/bd_65f4_m01arn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_51/sim/bd_65f4_m01rn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_52/sim/bd_65f4_m01awn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_53/sim/bd_65f4_m01wn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_54/sim/bd_65f4_m01bn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_55/sim/bd_65f4_m01e_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_56/sim/bd_65f4_m02s2a_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_57/sim/bd_65f4_m02arn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_58/sim/bd_65f4_m02rn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_59/sim/bd_65f4_m02awn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_60/sim/bd_65f4_m02wn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_61/sim/bd_65f4_m02bn_0.sv" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/ip/ip_62/sim/bd_65f4_m02e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/6dcf" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/80cc/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/22b9/hdl/verilog" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ipshared/f42d/hdl" +incdir+"C:/Xilinx/Vivado/2021.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/bd_0/sim/bd_65f4.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/ip/urllc_core_inst_1_smartconnect_outer_1/sim/urllc_core_inst_1_smartconnect_outer_1.v" \
    "$ref_dir/../../../../urllc-demo-vivado.gen/sources_1/bd/design_sender/bd/urllc_core_inst_1/sim/urllc_core_inst_1.v" \
    "$ref_dir/../../../bd/design_sender/ip/design_sender_xlconstant_0_0/sim/design_sender_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/design_sender/ip/design_sender_xlconstant_1_0/sim/design_sender_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/design_sender/sim/design_sender.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_sender xil_defaultlib.glbl -o design_sender_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_sender_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_sender.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_sender_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_sender_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_sender.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_sender.sh [-help]\n\
Usage: design_sender.sh [-lib_map_path]\n\
Usage: design_sender.sh [-reset_run]\n\
Usage: design_sender.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
