# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.runs/synth_1/design_reciever_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.cache/wt [current_project]
set_property parent.project_path G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/hdl/design_reciever_wrapper.v
add_files G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/urllc_core_inst_0.bd
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_dma_1_0/urllc_core_inst_0_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_dma_1_0/urllc_core_inst_0_axi_dma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_dma_1_0/urllc_core_inst_0_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_rst_ps7_0_200M_0/urllc_core_inst_0_rst_ps7_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_rst_ps7_0_200M_0/urllc_core_inst_0_rst_ps7_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_rst_ps7_0_200M_0/urllc_core_inst_0_rst_ps7_0_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_dma_0_0/urllc_core_inst_0_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_dma_0_0/urllc_core_inst_0_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_dma_0_0/urllc_core_inst_0_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_rst_ps7_0_120M_0/urllc_core_inst_0_rst_ps7_0_120M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_rst_ps7_0_120M_0/urllc_core_inst_0_rst_ps7_0_120M_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_rst_ps7_0_120M_0/urllc_core_inst_0_rst_ps7_0_120M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_gpio_0_0/urllc_core_inst_0_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_gpio_0_0/urllc_core_inst_0_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_gpio_0_0/urllc_core_inst_0_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_gpio_1_0/urllc_core_inst_0_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_gpio_1_0/urllc_core_inst_0_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_axi_gpio_1_0/urllc_core_inst_0_axi_gpio_1_0.xdc]
set_property used_in_synthesis false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_ila_0_0/urllc_core_inst_0_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_100M_0/urllc_core_inst_0_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_100M_0/urllc_core_inst_0_clk_wiz_100M_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_100M_0/urllc_core_inst_0_clk_wiz_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_dynamic_0/urllc_core_inst_0_clk_wiz_dynamic_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_dynamic_0/urllc_core_inst_0_clk_wiz_dynamic_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_dynamic_0/urllc_core_inst_0_clk_wiz_dynamic_0_late.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_dynamic_0/urllc_core_inst_0_clk_wiz_dynamic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_static_0/urllc_core_inst_0_clk_wiz_static_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_static_0/urllc_core_inst_0_clk_wiz_static_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_static_0/urllc_core_inst_0_clk_wiz_static_0_late.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_clk_wiz_static_0/urllc_core_inst_0_clk_wiz_static_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_proc_clock_reset_0/urllc_core_inst_0_proc_clock_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_proc_clock_reset_0/urllc_core_inst_0_proc_clock_reset_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_proc_clock_reset_0/urllc_core_inst_0_proc_clock_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_proc_data_reset_8M_0/urllc_core_inst_0_proc_data_reset_8M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_proc_data_reset_8M_0/urllc_core_inst_0_proc_data_reset_8M_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_proc_data_reset_8M_0/urllc_core_inst_0_proc_data_reset_8M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_1/bd_69e5_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_1/bd_69e5_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_2/bd_69e5_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_3/bd_69e5_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_4/bd_69e5_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_5/bd_69e5_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_6/bd_69e5_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_7/bd_69e5_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_8/bd_69e5_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_9/bd_69e5_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_10/bd_69e5_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_11/bd_69e5_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_12/bd_69e5_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_13/bd_69e5_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_14/bd_69e5_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_15/bd_69e5_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_16/bd_69e5_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_20/bd_69e5_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_21/bd_69e5_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_22/bd_69e5_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_23/bd_69e5_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_24/bd_69e5_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_25/bd_69e5_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_26/bd_69e5_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_27/bd_69e5_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_28/bd_69e5_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_29/bd_69e5_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_30/bd_69e5_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_31/bd_69e5_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_33/bd_69e5_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_34/bd_69e5_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_35/bd_69e5_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_36/bd_69e5_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_37/bd_69e5_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_38/bd_69e5_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_40/bd_69e5_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_41/bd_69e5_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_42/bd_69e5_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_43/bd_69e5_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_44/bd_69e5_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_45/bd_69e5_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_47/bd_69e5_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_48/bd_69e5_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_49/bd_69e5_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_50/bd_69e5_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_51/bd_69e5_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/bd_0/ip/ip_52/bd_69e5_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_0/ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_processing_system7_0_0/urllc_core_inst_0_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_1/bd_a924_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_1/bd_a924_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_2/bd_a924_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_3/bd_a924_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_4/bd_a924_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_5/bd_a924_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_6/bd_a924_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_10/bd_a924_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_11/bd_a924_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_12/bd_a924_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_13/bd_a924_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_14/bd_a924_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_15/bd_a924_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_19/bd_a924_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_20/bd_a924_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_21/bd_a924_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_25/bd_a924_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_26/bd_a924_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_27/bd_a924_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_28/bd_a924_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_32/bd_a924_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_33/bd_a924_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_34/bd_a924_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_38/bd_a924_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_39/bd_a924_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_40/bd_a924_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_41/bd_a924_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_42/bd_a924_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_43/bd_a924_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_44/bd_a924_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_45/bd_a924_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_46/bd_a924_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_47/bd_a924_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_49/bd_a924_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_50/bd_a924_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_51/bd_a924_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_52/bd_a924_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_53/bd_a924_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_54/bd_a924_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_56/bd_a924_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_57/bd_a924_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_58/bd_a924_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_59/bd_a924_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_60/bd_a924_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/bd_0/ip/ip_61/bd_a924_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/ip/urllc_core_inst_0_smartconnect_outer_1/ooc.xdc]
set_property used_in_implementation false [get_files -all G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/bd/urllc_core_inst_0/urllc_core_inst_0_ooc.xdc]

add_files G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.srcs/sources_1/bd/design_reciever/design_reciever.bd
set_property used_in_implementation false [get_files -all g:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.gen/sources_1/bd/design_reciever/design_reciever_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.srcs/constrs_1/imports/new/urllc.xdc
set_property used_in_implementation false [get_files G:/Chiro/Programs/urllc-demo-pynq/urllc-zynq-vivado/urllc-zynq-vivado.srcs/constrs_1/imports/new/urllc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_reciever_wrapper -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_reciever_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_reciever_wrapper_utilization_synth.rpt -pb design_reciever_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
