# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/urllc.xdc

# Block Designs: bd/urllc_fifo_receiver/urllc_fifo_receiver.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==urllc_fifo_receiver || ORIG_REF_NAME==urllc_fifo_receiver} -quiet] -quiet

# XDC: g:/Chiro/Programs/urllc-demo-pynq/urllc-vivado/urllc-fifo.gen/sources_1/bd/urllc_fifo_receiver/urllc_fifo_receiver_ooc.xdc
