set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad[0]}]
set_property PACKAGE_PIN P19 [get_ports {sender_ad[7]}]
set_property PACKAGE_PIN V20 [get_ports {sender_ad[6]}]
set_property PACKAGE_PIN P18 [get_ports {sender_ad[5]}]
set_property PACKAGE_PIN U20 [get_ports {sender_ad[4]}]
set_property PACKAGE_PIN N18 [get_ports {sender_ad[3]}]
set_property PACKAGE_PIN T20 [get_ports {sender_ad[2]}]
set_property PACKAGE_PIN N20 [get_ports {sender_ad[1]}]
set_property PACKAGE_PIN P20 [get_ports {sender_ad[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_da[0]}]
set_property PACKAGE_PIN T16 [get_ports {sender_da[7]}]
set_property PACKAGE_PIN T17 [get_ports {sender_da[6]}]
set_property PACKAGE_PIN R16 [get_ports {sender_da[5]}]
set_property PACKAGE_PIN U18 [get_ports {sender_da[4]}]
set_property PACKAGE_PIN P16 [get_ports {sender_da[3]}]
set_property PACKAGE_PIN V16 [get_ports {sender_da[2]}]
set_property PACKAGE_PIN W14 [get_ports {sender_da[1]}]
set_property PACKAGE_PIN Y14 [get_ports {sender_da[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {clk_pl_50M}]
set_property PACKAGE_PIN K17 [get_ports {clk_pl_50M}]

set_property IOSTANDARD LVCMOS33 [get_ports {sender_da_clk_120M}]
set_property PACKAGE_PIN R17 [get_ports {sender_da_clk_120M}]
set_property IOSTANDARD LVCMOS33 [get_ports {sender_ad_clk_8M}]
set_property PACKAGE_PIN W20 [get_ports {sender_ad_clk_8M}]

