# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/test_fifo_axis/ip/test_fifo_axis_axis_data_fifo_dac_0/test_fifo_axis_axis_data_fifo_dac_0.xci
# IP: The module: 'test_fifo_axis_axis_data_fifo_dac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/test_fifo_axis/ip/test_fifo_axis_axis_data_fifo_dac_0/test_fifo_axis_axis_data_fifo_dac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo_axis_axis_data_fifo_dac_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/test_fifo_axis/ip/test_fifo_axis_axis_data_fifo_dac_0/test_fifo_axis_axis_data_fifo_dac_0.xci
# IP: The module: 'test_fifo_axis_axis_data_fifo_dac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programs/urllc-demo-pynq/urllc-vivado-2018/urllc-vivado-2018.srcs/sources_1/bd/test_fifo_axis/ip/test_fifo_axis_axis_data_fifo_dac_0/test_fifo_axis_axis_data_fifo_dac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo_axis_axis_data_fifo_dac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
