webtalk_init -webtalk_dir D:\\Programs\\urllc-demo-pynq\\urllc-vivado-2018\\urllc-vivado-2018.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-02-08 17:21:13" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fcov655bq2evk2pdkmet2jr9vf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_27" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1797 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.499 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1644304248983" -context "sdk\\\\bsp/1644304248983"
webtalk_add_data -client sdk -key hwid -value "1643899352626" -context "sdk\\\\bsp/1644304248983"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1644304248983"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1644304248983"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1644304248983"
webtalk_add_data -client sdk -key uid -value "1644304256521" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key hwid -value "1643899352626" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key bspid -value "1644304248983" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1644304256521"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key DebugCount -value "21" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1644312073930"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1644312073930"
webtalk_transmit -clientid 475901561 -regid "" -xml D:\\Programs\\urllc-demo-pynq\\urllc-vivado-2018\\urllc-vivado-2018.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Programs\\urllc-demo-pynq\\urllc-vivado-2018\\urllc-vivado-2018.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Programs\\urllc-demo-pynq\\urllc-vivado-2018\\urllc-vivado-2018.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
